WhatsApp/erlfmt

- README.md
This is what I was trying to say with the comment, here https://github.com/WhatsApp/erlfmt/issues/13#issuecomment-632230417
> add formatting check to rebar3 config in readme, since it is now supported

- src/erlfmt.erl
- src/erlfmt_format.erl
- src/erlfmt_scan.erl
- src/rebar3_fmt_prv.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/attributes.erl
- test/erlfmt_SUITE_data/comments.erl
- test/erlfmt_SUITE_data/comments.erl.formatted
- test/erlfmt_SUITE_data/simple_comments.erl
- test/erlfmt_algebra_SUITE.erl
- test/erlfmt_format_SUITE.erl
- test/erlfmt_markdown_SUITE.erl
> erlfmt: remove empty lines below single line attributes

- src/erlfmt_parse.yrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
Starts addressing some issues described in https://github.com/WhatsApp/erlfmt/issues/39
> Fix some parser crashes 

- src/erlfmt_scan.erl
- test/erlfmt_format_SUITE.erl
> Trim trailing whitespace from comments

- README.md
This should help make it easier to spot how to integrate erlfmt with doom emacs
> how to integrate with doom emacs

- src/erlfmt_algebra.erl
This is a step to make the fits function more readable.
> erlfmt_algebra: rename parameters in fits function I -> Indent, etc.

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> group exports

- src/erlfmt.erl
- test/erlfmt_format_SUITE.erl
> preserve new lines between attributes

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> remove space between single clause funs and parens

- src/erlfmt.erl
- src/erlfmt_cli.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
- test/erlfmt_markdown_SUITE.erl
Replaces https://github.com/WhatsApp/erlfmt/pull/63
since both rebasing and merging lost too much information to recover.
Fixes #15
> --insert-pragma inserts an @format comment into a file

- StyleGuide.md
- test/erlfmt_markdown_SUITE.erl
Closes https://github.com/WhatsApp/erlfmt/issues/26
> Add style guide with runnable examples

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> erlfmt_format: export_type is grouped like export

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> Don't break multiple clauses with comments

- src/erlfmt.erl
- test/erlfmt_SUITE_data/attributes.erl
- test/erlfmt_format_SUITE.erl
> Preserve empty lines around if-like attributes

- README.md
- src/erlfmt.erl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/ignore_format.erl
- test/erlfmt_SUITE_data/ignore_format.erl.formatted
Fixes https://github.com/WhatsApp/erlfmt/issues/19
> erlfmt-ignore: ignores the next form and does not format it

- src/erlfmt.erl
- src/erlfmt_cli.erl
- src/erlfmt_format.erl
- src/erlfmt_recomment.erl
- src/erlfmt_scan.erl
- src/erlfmt_scan.hrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
- test/erlfmt_markdown_SUITE.erl
Adds parameter, so that we can start experimenting with a default line length, that will in future address https://github.com/WhatsApp/erlfmt/issues/17
> add print-width cli parameter and refactor public api

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> Do not preserve operator newline with a next break fits expression

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> Make try and after always introduce a newline

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> Preserve newline in list & binary comprehensions

- README.md
- RELEASE.md
> document release process

- src/erlfmt.erl
- test/erlfmt_SUITE.erl
> do not crash when formatting an empty file

- src/erlfmt_parse.yrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
> Support macros with parens in concat

- src/erlfmt.erl
- src/erlfmt_algebra.erl
- src/erlfmt_format.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE_data/attributes.erl
- test/erlfmt_SUITE_data/simple_comments.erl
- test/erlfmt_format_SUITE.erl
Fixes #167
This formatting decision is discussed in https://github.com/WhatsApp/erlfmt/pull/186
> change formatting of pipes to prefixes

- src/erlfmt_format.erl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/simple_comments.erl
- test/erlfmt_format_SUITE.erl
> fix issue with comments before a dot

- src/erlfmt.erl
- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> fix fold unions

- README.md
…as requested by @awalterschulze in AdRoll/rebar3_format#177.
BTW… I ❤️   the new stringified API… Thank you!
> Add integration to rebar3_format

- src/erlfmt.erl
- src/erlfmt_cli.erl
- test/erlfmt_format_SUITE.erl
> rename width to print_width

- src/erlfmt_parse.yrl
- test/erlfmt_format_SUITE.erl
> fix record field type end location

- Makefile
- README.md
- doc/RebarUsage.md
- src/erlfmt_cli.erl
> provide default value for --files when none is provided

- Makefile
- doc/RebarUsage.md
- rebar.config
- src/erlfmt_cli.erl
- test/erlfmt_SUITE.erl
Fixes #208 
Thanks to @TD5 for pairing with me on this
> exclude files

- src/erlfmt_recomment.erl
- test/erlfmt_format_SUITE.erl
Closes https://github.com/WhatsApp/erlfmt/issues/131
> Properly handle comments inside concats

- src/erlfmt_scan.erl
- test/erlfmt_format_SUITE.erl
Closes https://github.com/WhatsApp/erlfmt/issues/168
> Properly handle trailing comments followed by post-comments

- doc/erlfmt_parse.md
- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
Partially tackles https://github.com/WhatsApp/erlfmt/issues/125
> Preserve comments inside fun type arg list

- src/erlfmt.erl
- test/erlfmt_format_SUITE.erl
> no newline after spec

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
Fixes #230
Not sure if we want this change, but thought it might be good to see what it would look like
> preserve newlines after =

- src/erlfmt_parse.yrl
- test/erlfmt_format_SUITE.erl
> Support macros in type names

- src/erlfmt_cli.erl
Addresses a part of https://github.com/WhatsApp/erlfmt/issues/252
> add shorthand for --insert-pragma

- src/erlfmt_algebra.erl
- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/226
It feels like I cheated, maybe I am missing a test case
> dolon next break fits if there is no break between

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
This replaces the work done in https://github.com/WhatsApp/erlfmt/pull/198 and Fixes #136 and #149 and https://github.com/WhatsApp/erlfmt/issues/163
> rewrite binop using associativity

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
See commented out tests for the result we really want to achieve
> partially reverts #262 for equal and dolon to better support next break fits in future

- src/erlfmt_recomment.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/263
> fix pre dot comments in function

- src/erlfmt.erl
- test/erlfmt_SUITE.erl
Steal better error reporting from https://github.com/WhatsApp/erlfmt/compare/receive_clauses?expand=1
> better error reporting for not_equivalent and tests

- doc/FormattingDecisionAssociative.md
- doc/Readme.md
- test/erlfmt_format_SUITE.erl
Closes https://github.com/WhatsApp/erlfmt/issues/163
> formatting decision for left associativity of dolon and equal binary operators

- README.md
Fixes https://github.com/WhatsApp/erlfmt/issues/301
> document that enforcing line length is best effort

- src/erlfmt_cli.erl
fixes https://github.com/WhatsApp/erlfmt/issues/322
> fix typo in erlfmt_cli

- src/erlfmt_parse.yrl
> erlfmt_parse: clean up hipe pragmas

- src/erlfmt.erl
> Allow erlfmt:format_string/2 to set filename from option

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> Handle the Int#{} edge case without crashing

- src/erlfmt_parse.yrl
- test/erlfmt_format_SUITE.erl
> Handle try clause in define

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
> Support formatting PIDs, Refs and Ports

- src/erlfmt_parse.yrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
> Handle ;-separated guards in macro expressions

- src/erlfmt.erl
From https://github.com/WhatsApp/erlfmt/pull/337#discussion_r926289586
> Add config range spec to erlfmt:format_string/2
