- src/erlfmt.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
Adding the ability to format a specific range of a file. In this iteration
the function will either return a formatted string for the
area that is being reformatted, or a list of alternate ranges
which are ok, i.e. contains one or more forms.
In order to do this I'm also adding location annotations to raw_string in order to tell if the raw string is in the range that is being formatted.
> Adding ability to format range of file

- src/erlfmt.erl
- src/rebar3_fmt_prv.erl
I assumed getopt would return all plain arguments as multiple `{file, _}`
tuples, I was wrong - they are returned as the "extra options" and only
the first file is properly processed. This handles it correctly.
Tested manually both escript and plugin, we currently don't have a setup
for testing CLI.
> Process all files from command arguments

- src/erlfmt_algebra.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/overlong.erl
- test/erlfmt_SUITE_data/overlong.erl.formatted
Summary:
This improves formatting of situations where there are lines that cannot
be shortened - like a very long comment. This is achieved by having a
smarter "best_unfit" function in the algorithm.
> Fix formatting overlong lines

- rebar.config
- src/erlfmt.erl
- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_recomment.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
- test/erlfmt_markdown_SUITE.erl
This unblocks formatting files like `rebar.config`, but also simplifies
testing by unifying forms and expressions. We support both a sequence of
dot-terminated expressions as well as a single expression without a dot.
Additionally, since we can easily parse both forms and standalone expressions, there's
no need for two sets of macros in `erlfmt_format_SUITE`.
Closes #13
> Support parsing standalone expressions 

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> erlfmt_format: make list and binary comprehensions "next break fits"

- src/erlfmt.erl
- src/erlfmt_algebra.erl
- src/erlfmt_recomment.erl
- test/erlfmt_algebra_SUITE.erl
Add Facebook license to algebra and include Elixir copyright `Copyright (c) 2012-2020 Plataformatec` for algebra files.
> fix licenses and format

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
This is a follow-up to https://github.com/WhatsApp/erlfmt/commit/46eda2c639ef61eb245df0f54c739aed4f910e05 where we omitted this case.
> Concat converted from a string also forces breaks

- README.md
- reorders some sections in the readme
- adds top section purely focused on marketing to top of readme
- gives line length its own section
- adds examples of using erlfmt on the command line
> reorder and add marketing to readme

- rebar.config
- src/erlfmt.erl
- src/erlfmt_cli.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/pragma.erl
> Allow reading from stdin

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> erlfmt_format: make position of return type in specs consistent

- src/erlfmt_cli.erl
The reason not to use exit code 1 is that this can conflict with the `diff` tool's exit code, which uses exit code 1 to indicate that there was changes and doesn't reflect an actual error.
Since the `diff` tool can be quite commonly used with a formatter, we want this integration to be seamless on the command line
`$ erlfmt $FILE | diff -u $FILE -`
> catch and print out exceptions to standard error and never used exit code 1

- src/erlfmt_parse.yrl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
This was introduced to track newlines after certain tokens to implement the
"follow my lead" behaviour in lists & friends. But in the new implementation
in 0.2.0 we're using the location information directly to do that instead of
the newline annotations. Because of that they are not needed.
This effectively reverts 4246eb4287ca1c65ca2aea340ea5a182cbec8537.
> Remove newline annotation

- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/no_pragma.erl
These include:
* non-unicode codepoints in the file
* single form with trailing comment
> Fix require pragma for some edge cases

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
The key part of the fix is removing incorrect spec from `erlfmt_format:expr_to_algebra/1`.
This function accepts much more than just "exprs" as first element, for example special,
non-standalone nodes we've introduced like `args`, `clause`, `guard_and`, ...
> Fix dialyzer

- src/erlfmt.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
- test/erlfmt_markdown_SUITE.erl
This modifies format_string to expose as close of an API and return types
as it makes sense to `erlfmt:format_file`. This should also allow correctly
handling syntax errors in the passed string instead of crashing.
Additionally this adds the verification pass to `erlfmt:format_string`
Subsequently remove `erlfmt:contains_pragma_string` shrinking the size of the
public API.
> Make erlfmt:format_string API-compatible with erlfmt:format_file

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/rebar.config.script
- test/erlfmt_format_SUITE.erl
They can have multiple expressions between each dot, unlike .config files.
Add a special top-level exprs node to handle that situation.
> Correctly handle .script files

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
Helps with #76 unnecessary multiline layout for clauses with comments
> erlfmt_format: single line clauses with comments, stay single line clauses

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> erlfmt_format: dont group pipes so they all break together

- README.md
- src/erlfmt_format.erl
- src/erlfmt_scan.erl
- test/erlfmt_format_SUITE.erl
Fixes #72
This preserves empty lines between values in containers, like exports and records.
This required some refactoring, since the simple fold_doc now needed to not only be aware of the break, but also needed to have the original value, to be able to check for empty lines to preserve.
Really struggled to make this refactoring more readable and I guess it is debatable, whether I achieved that, so looking forward to ideas in the review.
Also needed to preserve the end line for better empty line detection.
Should probably do the same for inner end line, so maybe we can think of a better function name.
> erlfmt_format: preserve empty lines between values in containers

- src/erlfmt_format.erl
- src/erlfmt_recomment.erl
- test/erlfmt_format_SUITE.erl
Separate formatting of type unions from other operators - their format
seems distinct enough to warrant this and the code looks simpler.
Closes #89
> Fix multiline type unions formatting

- test/erlfmt_format_SUITE.erl
This pull request is just to facilitate a discussion.
I was busy writing up the formatting decision for issue #19 that we want to add an option to add a comment before a form, that opts it out of formatting, but then I thought about this idea.
Maybe there is still a way to avoid adding this option, as we want to keep options to a minimum.
Is it possible ask users to group their lists, using lists?
Since then you can still get a reasonably formatted DSLish list.
See here the formatted DSLish list, with the intended lines, grouped in lists:
```erlang
gen_part_decode_funcs({constructed, bif}, TypeName, {_Name, parts, Tag, _Type}) ->
emit([
["  case Data of", nl],
["    L when is_list(L) ->", nl],
["      'dec_", TypeName, "'(lists:map(fun(X) -> element(1, "],
[{call, ber, ber_decode_erlang, …
```
> an example of formatting a dslish list with grouping

- StyleGuide.md
Using `rebar3_lint` / `elvis`, you can automate most of the "manual" work required for linting.
I think it's a good idea to guide folks that reach this page from the broader Erlang ecosystem to a tool that can help them with that, just like `erlfmt` can help them with formatting.
I would also like to recommend you to take a look at the [Erlang Guidelines](https://github.com/inaka/erlang_guidelines). Maybe you can contribute some updates based on what's here and we can unify the list, to provide a single comprehensive guide for newcommers.
> Add references to Elvis/Linter rules.

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> preserve new lines in guards

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
> Make multi-line tuples & binaries next-break-fits

- rebar.config
This removes user's CWD from the file debug info and in consequence from stacktraces.
We don't need this in production releases.
> Use deterministic compiler option for releasing precompiled escript

- .github/workflows/ci.yml
- src/erlfmt.erl
- src/erlfmt_cli.erl
- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
Fixes #12 
Before formatting I only ran this task and got the following output
https://github.com/WhatsApp/erlfmt/runs/1066854528?check_suite_focus=true
After formatting, checks pass
I had to include removing the generated parser, as this is not committed into the repo and not formatted on generation, so we probably should not check it.
> erlfmt erlfmt and keep it that way

- .github/CONTRIBUTING.md
- README.md
I also:
- moved a few things around, which I think makes for a nicer order.
- Changed erl to erlang, since then I get highlighting when I edit the readme not only when I view the rendered version.
- Added formatting to the contributing guidelines
> Readme: add table of contents

- src/erlfmt_parse.yrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
This changes the `=>` and `:=` operators from special to maps
to generic operators that can form valid expresions anywhere,
and maps to `#{ any_expression... }` instead of only accepting
the map operators.
This allows easily supporting map expressions behind macros.
Closes #137
> Relax map syntax

- src/erlfmt.erl
- src/erlfmt_cli.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
Changed --check to rather use format_string, this way stdin is also supported and API is simpler.
```sh
$ rebar3 as release escriptize
$ _build/release/bin/erlfmt --check "{src,include,test}/*.{hrl,erl}" "rebar.config"
Checking formatting...
[warn] src/erlfmt_cli.erl
[warn] src/erlfmt_scan.erl
[warn] test/erlfmt_SUITE.erl
[warn] Code style issues found in the above file(s). Forgot to run erlfmt?
$ _build/release/bin/erlfmt -w "{src,include,test}/*.{hrl,erl}" "rebar.config"
$ git diff
...
modified:   src/erlfmt_cli.erl
modified:   src/erlfmt_scan.erl
modified:   test/erlfmt_SUITE.erl
...
$ _build/release/bin/erlfmt --check "{src,include,test}/*.{hrl,erl}" "rebar.config"
Checking formatting...
All matched files use erlfmt code style!
```
> rather use format_string for checking

- rebar.config
As suggested by @paulo-ferraz-oliveira https://github.com/WhatsApp/erlfmt/issues/178#issuecomment-696976024
> set minimum otp version in rebar config

- README.md
- src/rebar3_fmt_prv.erl
With the old recommendation of rebar config, it was difficult (impossible?) to run `rebar3 fmt --check` in CI and have it check formatting.
This PR changes the recommended setup so that the command users must run in order to format things is `rebar3 fmt --write`, not just `rebar3 fmt`. Then they can do `rebar3 fmt --check` in CI.
I probably have not thought through all the implications or updated all the places that need to be updated, so please consider this a "discussion" PR.
> Update instructions for integration with rebar and CI

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
Fixes #178
attributes can have zero parameters, for example:
```erlang
-endif().
```
For more details on how this was discovered, see the issue
> parse attributes with empty parens

- src/erlfmt_recomment.erl
- test/erlfmt_format_SUITE.erl
This does not fix #125 , but it stops it from crashing at least.
> fix crash with comments in catch

- README.md
plugins are also downloaded if the project is a transitive dependency,
project_plugins are downloaded only when working directly on the codebase.
For the tasks erlfmt is used for normally, project_plugins seems more
appropriate
> Recommend to use project_plugins instead of plugins in readme.

- README.md
- doc/RebarUsage.md
- src/erlfmt.erl
- src/erlfmt_cli.erl
- src/rebar3_fmt_prv.erl
This gives command line arguments preference over arguments specified in the rebar3 config.
This Fixes #177
And fixes #141
Given the following config
```erlang
{erlfmt, [
write,
{files, "{src,include,test}/*.{hrl,erl}"}
]}.
```
```sh
rebar3 fmt # formats all files in place
rebar3 fmt ./src/example.app.src # only formats the single file
rebar3 fmt --check # checks all files and doesn't format
rebar3 fmt -o ./out/ # outputs formatted files folder and doesn't format the original
rebar3 fmt -o out src/*.erl # formats only selected files and outputs them to selected folder
```
```
{erlfmt, [
check,
require_pragma,
verbose,
{width, 100},
{files, ["{src,include,test}/*.{hrl,erl,app.src}", "rebar.config"]}
]}.
```
Got error:
```
unknown option: {width,100}
Usage: rebar3 fmt [-h] [-v] [-w] [-o …
```
> better rebar3 integration

- src/erlfmt_parse.yrl
- test/erlfmt_format_SUITE.erl
Fixes #181
When debugging 181 I found that 
```erlang
name =>
{local, Name :: atom()} |
{global, GlobalName :: any()} |
{via, Module :: atom(), ViaName :: any()}
```
Was parsed as
```
name =>
{local, Name :: atom()}
```
and then the rest, but the pipe needed to bind tighter than the `=>` operator.
> bind pipe tighter

- src/erlfmt.erl
- src/erlfmt_cli.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/overlong.erl
- test/erlfmt_SUITE_data/overlong.erl.formatted
Closes #120
Use a map in the return values of the format functions, so that more return data can be added.
Add "verbose warnings", which are only printed if the verbose option is given.
> Warn on long lines

- src/erlfmt_algebra.erl
- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
@mheiber `::` is double colon or dolon
Fixes #223
> preserve breaks after dolon

- src/erlfmt.erl
This allows you to both read nodes and format them later.
> Export the format_nodes/2 function

- src/erlfmt_cli.erl
Fixes #231. I couldn't find any test that checks the writing to but let me know if you think it is needed and I'll try to implement one.
I used `stats` to check if it works: 
```bash
$ stat rebar.config | grep -F 'Modify'                                                                                                                                            0s
Modify: 2021-01-06 09:38:08.204419183 +0000
$ _build/release/bin/erlfmt -w "{src,include,test}/*.{hrl,erl}" rebar.config
$ stat rebar.config | grep -F 'Modify'                                                                                                                                            0s
Modify: 2021-01-06 09:38:08.204419183 +0000
```
> Only write to file the formatted code when it is different to the current one

- erlang_ls.config
- src/erlfmt.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/broken.erl.formatted
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/233
`erlfmt_SUITE_data/attribute.erl` already tests quite a few cases of preserving empty lines.
Added one test to make sure that more than one empty line is reduced to a single empty line.
> preserve a single empty line between attributes

- src/erlfmt_recomment.erl
- test/erlfmt_format_SUITE.erl
> fix: Crash formatting qlc_SUITE in OTP

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/228
> Preserve newlines between separated guards

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
Tackled parts of https://github.com/WhatsApp/erlfmt/issues/125 , but issues with receive statements persist and will be tackled at a later date.
> Adjust AST for try clauses such that they do not move comments around

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/180
> preserve newline after's arrow

- doc/FormattingDecisionListComprehensions.md
- src/erlfmt.erl
- src/erlfmt_format.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/simple_comments.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/148
I have created an updated version of formatting for list comprehensions
It is something we can look at while to help inform our decision in https://github.com/WhatsApp/erlfmt/issues/148
This is the implementation for the option
```erlang
[
function_with_long_name(A)
|| {A, B} <- Cs,
filter(B)
]
```
> updated formatting for list comprehensions to dedent double pipes just a little

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/211
I think we have used this trick before where we modify the expression and replace it with a non-existent expression to send signal of the context, such that the special case is only applied in a specific context.  In this case I replace the `op` `=` with `op` `clause_pattern`
> double indent pattern matches in clauses

- src/erlfmt_parse.yrl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/260
Seems `erl_anno:location` crashes, since we have a `erlfmt_scan:anno()` and not a type from `erl_anno`.
I changed to it rather call `erlfmt_scan:get_anno(location, Anno)` as I assume this is what was intended.
Also fixed the type annotation for `token()` to point to `erlfmt_scan:token()` as pointed out by @gomoripeti 
```
-spec parse_node(Tokens) -> {ok, AbsNode} | {error, ErrorInfo} when
Tokens :: [token()],
AbsNode :: abstract_node(),
ErrorInfo :: error_info()
```
Since it seems the tokens passed to parse_node come from
```
-spec string_node(string()) -> node_ret().
```
where `node_ret()` is:
```
-type node_ret() ::
{ok, [token()], [comment()], state()}
| {error, {erl_anno:location(), module(), term()}, erl_anno:location()}
| {eof, …
```
> fix parsing of bad records

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_format_SUITE.erl
Removes `insert_expr_list` for `spec_clause`, since it always has a single body element.
This partially addresses https://github.com/WhatsApp/erlfmt/issues/125
I have also added tests to showcase that sometimes comments move before a `;` and to after a `when`, but I think these moves are in the acceptable range.
> spec_clause body is always a single element

- src/erlfmt_format.erl
- test/erlfmt_SUITE_data/comments.erl.formatted
- test/erlfmt_format_SUITE.erl
Possibly fixes https://github.com/WhatsApp/erlfmt/issues/272
This makes the following a mirror of each other:
`clause_to_algebra({clause, _Meta, Head, empty, Body}) ->`
`clause_to_algebra({spec_clause, _Meta, Head, Body, empty}) ->`
This means we remove a `group` around `nest`, which when the spec parameters breaks the space after `->` return also breaks.
An alternative would be to keep the group, but add 
`MaybeForce = maybe_force_break(has_break_between(Head, Body))`
`group(nest(concat([MaybeForce, <<"->">>, break(<<" ">>), BodyD]), ?INDENT))`
But then maybe we should do the same for the other two `clause_to_algebra`s for consistency?
> preserve newline in spec without guards

- src/erlfmt_format.erl
- test/erlfmt_format_SUITE.erl
I decided to make `clause_to_algebra` a special case for `spec_clause` using `maybe_force_breaks`
The reason to try this alternative is to avoid cases such as:
```
-spec use_credit(
store:id(),
decimal:decimal(),
binary() | null,
credit | {refund | dispute, binary()},
binary() | null
) ->
ok.
use_credit(...
```
which is really popular in the whatsapp code base.
This version preserves the newline after spec, but does not force it when the function parameters for the spec breaks.
The reason I made spec_clause a special case is that for other clause types there is a conflict with the break behaviour in clauses https://github.com/whatsapp/erlfmt#in-clauses where breaking the first one should result in breaking all clauses.
> preserve spec alternative

- src/erlfmt.erl
- src/erlfmt_scan.erl
- test/erlfmt_SUITE.erl
I noticed that for unparseable forms erlfmt parser returns incorrect end_location. The end_location is not used by erlfmt itself, but it can be useful for other tools. I'm unsure where a new testcase would fit as this internal thing does not affect formatting at all.
An example: (end column is the number of tokens (8) instead of the correct value 26)
```
1> {ok, Forms, _Warnings} = erlfmt:read_nodes_string("nofile", "f() -> \"very long string\""), Forms.
[{raw_string,#{end_location => {1,8},location => {1,1}},
"f() -> \"very long string\""}]
2> length("f() -> \"very long string\"").
25
```
> Fix end_location in raw_string anno

- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_recomment.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/simple_comments.erl
- test/erlfmt_format_SUITE.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/125
Before this diff the following test would have passed where the comment is moved from before the `after` to above the `after`
```erlang
?assertFormat(
"receive\n"
"after\n"
"    % before zero\n"
"    0 -> ok\n"
"end\n",
"receive\n"
"% before zero\n"
"after 0 -> ok\n"
"end\n"
),
```
> Preserve comments in receive after after

- src/erlfmt.erl
- src/erlfmt_cli.erl
- test/erlfmt_SUITE.erl
Once a codebase has fully adopted `erlfmt` it would be nice to remove all previously added pragmas.
I hope to use the same type of code to replace the current implementation of `insert_pragma` to be able to also replace a pragma with a new style of pragma that is compatible with edoc, see https://github.com/WhatsApp/erlfmt/issues/277
> delete pragma command line argument

- doc/FormattingDecisionComments/module_comments.md
- doc/FormattingDecisionComments/module_comments.sh
I've added a deeper analysis of the number of percentages used for module documentation.
I hope this guides the project recommendation of `%%% @format`  as opposed to the proposed `%% @format` heading.
Any feedback welcomed
> Analysis: Number of percentages used for module documentation

- doc/ErlangFormatterComparison.md
- doc/RebarUsage.md
- src/erlfmt.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/pragma.erl
Fixes https://github.com/WhatsApp/erlfmt/issues/277
Some context: Marc-Andre has shown me an analyses of triple comments that removes the bias in my analyses, that shows that they are actually popular in erlang before the module attribute.  We will work on pushing this analyses to the repo, but I think we should adopt this style in insert pragma
> comment the @format pragma to avoid edoc warnings

- src/erlfmt.erl
- test/erlfmt_SUITE.erl
Got the following error: `function_clause,[{string,take_l,\n ... `
in `replace_pragma_comment_block`
Seems `replace_pragma_comment_block` couldn't handle empty lines in the comment block.
> fix replace pragma for empty lines

- src/erlfmt_parse.yrl
Erlfmt prododuces a lot of warnings, but other than that seems to do
mosttly the right thing - not touching the part that's not Erlang code.
> Format erlfmt_parse.yrl

- src/erlfmt.erl
- test/erlfmt_SUITE.erl
[Format range] Introduce functions to format enclosing range.
Context: For now we cannot format more granularly than top level forms.
Existing internal functions expect the passed range to cover exactly entire forms.
In prospect of user-friendly CLI, we introduce formatting entry points
that cover all the top level forms intersecting with passed range.
> [Format range] Introduce functions to format enclosing range.

- src/erlfmt.erl
Follow standard practice, so that client code can detect if there is an issue.
We already returned error code 2 in other cases of option parsing failure,
now everything is covered in a consistent manner.
> Return exit code 2 when option isn't recognized.

- README.md
- src/erlfmt_format.erl
- test/erlfmt_SUITE_data/overlong.erl
- test/erlfmt_SUITE_data/overlong.erl.formatted
- test/erlfmt_format_SUITE.erl
See the readme for description of the new format.
This is added to limit the vertical expansion of calls when the function overflows by only few characters.
Any code formatted today won't be affected by this change thanks to the format-preserving behaviour. Only new, unformatted code once formatted will be able to observe this behaviour.
> Introduce semi-expanded format for function calls

- README.md
- src/erlfmt_format.erl
- test/assert_diagnostic_SUITE.erl
- test/erlfmt_SUITE_data/comments.erl
- test/erlfmt_SUITE_data/comments.erl.formatted
- test/erlfmt_format_SUITE.erl
This change implements the semi-expanded format introduced for function calls in https://github.com/WhatsApp/erlfmt/pull/305 to all the containers.
> Introduce semi-expanded format for all containers

- src/erlfmt_cli.erl
Since the `io:setopts` call is done in the escript `main`, it doesn't carry over to `rebar3 fmt` and breaks `rebar3 fmt -`. By adjusting the `standard_io` opts when actually reading from stdin and reverting back, this should work now.
> Ensure the correct IO opts when reading from stdin

- src/erlfmt_parse.yrl
- test/erlfmt_format_SUITE.erl
If you run erlfmt on a file like this:
```
-module(testar).
-define(tjo(A), A -> ok).
apa(B) ->
case B of
?tjo(1)
;
?tjo(2)
end.
```
Then you will get this error
testar.erl:8:4: syntax error before: ';'
and the apa function will not be formatted. (There is another error also for the define, but that is not solved by the current PR)
The parse error is due to the parser not allowing a macro as the whole case clause and thus gets a parse error when getting to the semi-colon. This kind of macro usage is found in the code base I work with. With this PR, the apa function can be parsed and is successfully formatted.
> Allow macro as case clause.

- src/erlfmt_parse.yrl
> Fix "expression updates a literal" warning for OTP 27

- README.md
- src/erlfmt.erl
- test/erlfmt_SUITE_data/ignore_format.erl
- test/erlfmt_SUITE_data/ignore_format.erl.formatted
- test/erlfmt_SUITE_data/ignore_format_many.erl
- test/erlfmt_SUITE_data/ignore_format_many.erl.formatted
Right now only trailing spaces and `%` are allowed in an `erlfmt-ignore`. We make it so that anything after the `erlfmt-ignore` is discarded, effectively allowing for the user to document why formatting is disabled
> Allow providing an optional reason when using erlfmt-ignore

- README.md
- src/erlfmt.erl
- test/erlfmt_SUITE.erl
- test/erlfmt_SUITE_data/ignore_format.erl
- test/erlfmt_SUITE_data/ignore_format_many.erl
- test/erlfmt_SUITE_data/ignore_format_many.erl.formatted
- test/erlfmt_SUITE_data/ignore_format_many_old.erl
- test/erlfmt_SUITE_data/ignore_format_many_old.erl.formatted
- test/erlfmt_SUITE_data/ignore_format_old.erl
- test/erlfmt_SUITE_data/ignore_format_old.erl.formatted
This puts erlfmt in line with other tools that use the format `toolname:ignore` to disable warnings, and makes it easier for developers to "guess" the correct incantation
> Allow erlfmt:ignore to be used in addition to erlfmt-ignore

- src/erlfmt_cli.erl
- test/erlfmt_cli_SUITE.erl
When calling `erlfmt` with absolute paths for the files to format, the excludes don't apply, even if the resolved paths of the excludes would match the files to format.
Resolve the paths of the excludes based on the current working directory and add them to the excludes.
This issue was observed when using the
[VS Code Erlang Formatter extension](https://marketplace.visualstudio.com/items?itemName=szTheory.erlang-formatter). The extension invokes `rebar3 fmt` with the full path of the file to format.
> Apply `exclude_files` to `files` absolute paths

- .github/workflows/ci.yml
- src/erlfmt_format.erl
- src/erlfmt_parse.yrl
- src/erlfmt_scan.erl
- test/erlfmt_format_SUITE.erl
Sigils: https://www.erlang.org/blog/highlights-otp-27/#sigils
Triple Quoted Strings: https://www.erlang.org/blog/highlights-otp-27/#triple-quoted-strings
Also adds tests for documentation attributes. See: https://www.erlang.org/blog/highlights-otp-27/#overhauled-documentation-system
Resolves #355
> Support for OTP 27 Sigils & Triple Quoted Strings

- rebar.config
If this parameter is not specified explicitly, erlfmt cannot be installed under a non-standard name:
% cp _build/release/bin/erlfmt erlfmt-1.5.0
% ./erlfmt-1.5.0
escript: exception error: undefined function 'erlfmt-1.5':main/1
...
> Set escript main parameter

- src/erlfmt_parse.yrl
- test/erlfmt_format_SUITE.erl
They will be just removed when formatting, allowing more "sloppy" code before reformatting, increasing usability of erlfmt.
> Support trailing commas and semis

- src/erlfmt.erl
- test/erlfmt_SUITE_data/ignore_format_many.erl
- test/erlfmt_SUITE_data/ignore_format_many.erl.formatted
Erlfmt currently can't parse two contiguous `erlfmt:ignore-begin` / `erlfmt:ignore-end` blocks. When we parse the first `ignore-end` we leave the formatter in an "end" state and don't clear it before the next "begin" since we don't run `ignore_state_pre` or `ignore_state_post` until the next non-comment. erlfmt doesn't handle transitions from `end` to `begin`, resulting in an error.
After checking the code, it's unclear to me why we need an `end` state in the first place - we always end up transforming it in `false` whenever we start or finish processing a statement. On this PR I'm simplifying things by simply setting the state to `false` after an `erlfmt:ignore-end` statement.
The unit test added fails in master and can be used to confirm the fix.
> Fix bug where two contiguous ignore-begin blocks results in an error

- rebar.config
It turns out that when running dialyzer through rebar, - it would not by default report unknown types. `erlfmt` (after a series of refactorings such as `abstract_form()` -> `abstract_node()`) ended up in using not up-to-date types.
This PR is about opening a discussion for fixing types and specs in `erlfmt`. It cannot be landed yet AS IS in main, - since CI becomes red. I plan to fix types and specs properly in upcoming commits to this diff.
> stronger dialyzer checks

- src/erlfmt.erl
- src/erlfmt_cli.erl
By default, IO operations are serialised through the file server, which can add significant overhead. Moreover, we don't need the features of a fileserver here (multiple processes accessing a file at once, remote file access, etc.). As such, we bypass this using the `raw` option or the `prim_file` module (depending on context) to get a nice littler performance boost.
Relevant docs: https://www.erlang.org/doc/apps/kernel/file.html#module-performance
> Bypass file server to improve IO performance
